
name: yggdrasil
channels:
  - conda-forge
  - bioconda
  - defaults
  - anaconda
dependencies:
  - python
  - pip
  - biopython==1.71
  - dash==1.7.0
  - gunicorn==19.9.0
  - numpy==1.17.4
  - pandas==0.24.2
  - pip:
    - ipykernel
    - jupyter_client
    - matplotlib
    - plotly
    - tqdm
    - python-time
    - requests
    - quote
    - opentree
    - nbformat